version: "3.2"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
      - phpmyadmin
      - mysqldb
      - php

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - 6379:6379

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_app
    expose:
      - "80"
    links:
      - mysqldb
    ports:
      - "85:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - default

  mysqldb:
    restart: unless-stopped
    image: mariadb
    container_name: db-mysql
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - DATA_MYSQL:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - default

  php:
    restart: unless-stopped
    build: ./www
    container_name: apache-php-server
    expose:
      - "80"
    links:
      - mysqldb
    ports:
      - "8080:80"
    networks:
      - default

volumes:
  DATA_MYSQL: {}

networks:
  default:
    ipam:
      driver: default
